# Generated by Django 2.2.5 on 2020-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addusermodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
