# Generated by Django 2.2.5 on 2020-06-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusBooking', '0002_auto_20200621_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addusermodel',
            name='gender',
        ),
    ]
