# Generated by Django 2.2.5 on 2020-06-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusBooking', '0003_remove_addusermodel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRouteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_from', models.CharField(max_length=30)),
                ('bus_to', models.CharField(max_length=30)),
                ('journey_time', models.IntegerField()),
                ('price_per_seat', models.IntegerField()),
            ],
        ),
    ]
