# Generated by Django 2.2.5 on 2020-06-23 06:51

import BusBooking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusBooking', '0004_addroutemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroutemodel',
            name='route_id',
            field=models.IntegerField(default=BusBooking.models.AddRouteModel.number, unique=True),
        ),
        migrations.AlterField(
            model_name='addroutemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
