# Generated by Django 2.2.5 on 2020-06-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusBooking', '0005_auto_20200623_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addroutemodel',
            old_name='bus_from',
            new_name='Bus_from',
        ),
        migrations.RenameField(
            model_name='addroutemodel',
            old_name='bus_to',
            new_name='Bus_to',
        ),
        migrations.RenameField(
            model_name='addroutemodel',
            old_name='journey_time',
            new_name='Journey_time',
        ),
        migrations.RenameField(
            model_name='addroutemodel',
            old_name='price_per_seat',
            new_name='Price_per_seat',
        ),
        migrations.RenameField(
            model_name='addroutemodel',
            old_name='route_id',
            new_name='Route_id',
        ),
    ]
