# Generated by Django 2.2.5 on 2020-06-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusBooking', '0006_auto_20200623_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addusermodel',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='addusermodel',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='addusermodel',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='addusermodel',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='addusermodel',
            old_name='phone',
            new_name='Phone',
        ),
    ]
