# Generated by Django 2.2.5 on 2020-06-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusBooking', '0009_auto_20200630_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
