# Generated by Django 2.2.5 on 2020-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusBooking', '0010_transactions_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='Name',
            new_name='Passenger_name',
        ),
        migrations.AddField(
            model_name='transactions',
            name='User_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
